from importlib.metadata import version

__version__ = version("k3net")

from .net import (
    INN,
    LOCALHOST,
    PUB,
    InvalidIP4,
    InvalidIP4Number,
    IPUnreachable,
    NetworkError,
    choose_by_idc,
    choose_by_regex,
    choose_inn,
    choose_ips,
    choose_pub,
    get_host_devices,
    get_host_ip4,
    ip_class,
    ip_to_num,
    ips_prefer,
    is_inn,
    is_ip4,
    is_ip4_loopback,
    is_pub,
    num_to_ip,
    parse_ip_regex_str,
)

__all__ = [
    "INN",
    "LOCALHOST",
    "PUB",
    "IPUnreachable",
    "InvalidIP4",
    "InvalidIP4Number",
    "NetworkError",
    "choose_by_idc",
    "choose_by_regex",
    "choose_inn",
    "choose_ips",
    "choose_pub",
    "get_host_devices",
    "get_host_ip4",
    "ip_class",
    "ip_to_num",
    "ips_prefer",
    "is_inn",
    "is_ip4",
    "is_ip4_loopback",
    "is_pub",
    "num_to_ip",
    "parse_ip_regex_str",
]
